// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_Qz7FCjrbVWgYUzWVVBU99JmyZcFoOg',
    appId: '1:143748419578:web:add400ded570a0f4235e43',
    messagingSenderId: '143748419578',
    projectId: 'flutter-9d1a3',
    authDomain: 'flutter-9d1a3.firebaseapp.com',
    storageBucket: 'flutter-9d1a3.firebasestorage.app',
    measurementId: 'G-KGL1VDV1JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_Qz7FCjrbVWgYUzWVVBU99JmyZcFoOg',
    appId: '1:143748419578:android:add400ded570a0f4235e43',
    messagingSenderId: '143748419578',
    projectId: 'flutter-9d1a3',
    storageBucket: 'flutter-9d1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_Qz7FCjrbVWgYUzWVVBU99JmyZcFoOg',
    appId: '1:143748419578:ios:add400ded570a0f4235e43',
    messagingSenderId: '143748419578',
    projectId: 'flutter-9d1a3',
    storageBucket: 'flutter-9d1a3.firebasestorage.app',
    iosBundleId: 'com.example.repasoprueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_Qz7FCjrbVWgYUzWVVBU99JmyZcFoOg',
    appId: '1:143748419578:macos:add400ded570a0f4235e43',
    messagingSenderId: '143748419578',
    projectId: 'flutter-9d1a3',
    storageBucket: 'flutter-9d1a3.firebasestorage.app',
    iosBundleId: 'com.example.repasoprueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi_Qz7FCjrbVWgYUzWVVBU99JmyZcFoOg',
    appId: '1:143748419578:windows:add400ded570a0f4235e43',
    messagingSenderId: '143748419578',
    projectId: 'flutter-9d1a3',
    authDomain: 'flutter-9d1a3.firebaseapp.com',
    storageBucket: 'flutter-9d1a3.firebasestorage.app',
    measurementId: 'G-KGL1VDV1JY',
  );
}
