// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5FpZnsj7UhN7jl28oeW5b_5zTZZZn5x0',
    appId: '1:1029119758525:web:9d1aff954be0ab86ce27d4',
    messagingSenderId: '1029119758525',
    projectId: 'proyecto-8a636',
    authDomain: 'proyecto-8a636.firebaseapp.com',
    storageBucket: 'proyecto-8a636.firebasestorage.app',
    measurementId: 'G-F6RW3FKP7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5FpZnsj7UhN7jl28oeW5b_5zTZZZn5x0',
    appId: '1:1029119758525:android:9d1aff954be0ab86ce27d4',
    messagingSenderId: '1029119758525',
    projectId: 'proyecto-8a636',
    storageBucket: 'proyecto-8a636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FpZnsj7UhN7jl28oeW5b_5zTZZZn5x0',
    appId: '1:1029119758525:ios:9d1aff954be0ab86ce27d4',
    messagingSenderId: '1029119758525',
    projectId: 'proyecto-8a636',
    storageBucket: 'proyecto-8a636.firebasestorage.app',
    iosBundleId: 'com.example.repasoprueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FpZnsj7UhN7jl28oeW5b_5zTZZZn5x0',
    appId: '1:1029119758525:macos:9d1aff954be0ab86ce27d4',
    messagingSenderId: '1029119758525',
    projectId: 'proyecto-8a636',
    storageBucket: 'proyecto-8a636.firebasestorage.app',
    iosBundleId: 'com.example.repasoprueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5FpZnsj7UhN7jl28oeW5b_5zTZZZn5x0',
    appId: '1:1029119758525:windows:9d1aff954be0ab86ce27d4',
    messagingSenderId: '1029119758525',
    projectId: 'proyecto-8a636',
    authDomain: 'proyecto-8a636.firebaseapp.com',
    storageBucket: 'proyecto-8a636.firebasestorage.app',
    measurementId: 'G-F6RW3FKP7B',
  );
}
